### ISSUE TITLE
Don't ignore locale for `IfModifiedSince`

### ISSUE THREAD

**Issue by tindzk** [darkfrog26/outrnet#4]
I'm getting the following exception because Firefox sends the `IfModifiedSince` header in a non-English locale:

```
site 2015.07.15 11:30:34:266 [qtp710714889-447] ERROR c.o.n.h.s.OUTRNetServlet$ - java.text.ParseException: Unparseable date: "r, 15 lip 2015 11:27:10 GMT"
site    at java.text.DateFormat.parse(DateFormat.java:366)
site    at com.outr.net.http.request.HttpRequestHeaders.date(HttpRequestHeaders.scala:46)
site    at com.outr.net.http.request.HttpRequestHeaders.IfModifiedSince$lzycompute(HttpRequestHeaders.scala:10)
site    at com.outr.net.http.request.HttpRequestHeaders.IfModifiedSince(HttpRequestHeaders.scala:10)
```

This seems to be related to https://issues.jenkins-ci.org/browse/JENKINS-4021, but the suggested solution of iterating over all locales is far from efficient.

**Comment by darkfrog26** [comment]
Here's the spec:

http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.3

I'll have to dig a bit deeper to figure out how to determine this.  Can you send me the other headers so I can use them to write a test case for this?  I think I'm going to have to first parse the locale from the headers.

**Comment by tindzk** [comment]
Here is the list of headers:

Map(Referer -> http://localhost:8801/library/market/image.html, If-Modified-Since -> Wt, 23 cze 2015 21:35:01 GMT, Connection -> keep-alive, Accept -> _/_, Cache-Control -> max-age=0, Cookie -> ZooxoosSite=ae1a8c8d1f1a7a8db08557945352a1ad, Accept-Language -> pl,en;q=0.5, Accept-Encoding -> gzip, deflate, User-Agent -> Mozilla/5.0 (X11; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0, Host -> localhost:8801)

**Comment by darkfrog26** [comment]
The date is Tuesday, June 23 2015?

**Comment by tindzk** [comment]
Yes.
